Auth setup
shivshankar12345/pet-food-ecommerce-backend pull request #3
Opened 2024-09-24 13:43 UTC by mechlin-sda-shahnawaaz

Added the Otp based authentication for both signin and signup, however some minor bugs is remaining which will be fixed by tomorrow.

2024-09-24 14:17 UTC, shivshankar12345 requested changes

2024-09-24 14:17 UTC, shivshankar12345 commented on src/index.ts
> -    res.status(err.statusCode).json({ success: false, message: err.message });
Make a common class for responses and use it.

2024-09-24 14:17 UTC, shivshankar12345 commented on src/services/otp.service.ts
> +    };
If not required, then remove the comments.

2024-09-26 06:21 UTC, mechlin-sda-shahnawaaz commented on src/services/otp.service.ts
> +    };
Fixed Comments

2024-09-26 11:40 UTC, shivshankar12345 approved these changes

2024-09-26 11:40 UTC, merged